######################################################################
# Automatically generated by qmake (2.01a) ??????? ?????? 24 14:31:13 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += console

# Input
HEADERS += ../../registryreader.h \
    ../../registryentry.h
SOURCES += RegistryReaderTest.cpp \
           ../../registryreader.cpp \
    ../../registryentry.cpp

		  



